### ISSUE TITLE
Price bot to monitor harmony DEXs

### ISSUE THREAD

**Issue by gupadhyaya** [harmony-one/hackathon#4]
Replicate the Dapp-university's price bot example, but for DEXs on harmony. Submit the code as PR and place the price-bot under projects/ folder

Reference: https://github.com/dappuniversity/price-bot

Reward
* 500 ONE w/o video
* 1000 ONE w/ video

**Comment by vikramIde** [comment]
Taking this one 

Will finish this tomorrow

**Comment by givp** [comment]
@vikramIde any updates?

**Comment by Severino** [comment]
Implemented this #35

**Comment by Severino** [comment]
video:
https://youtu.be/_OsU7CpWVnk
address:
one1t9sqr030dr05t9kdxq73rytewktu2e6rxqj23g

**Comment by givp** [comment]
Thank you @Severino looks great.
