### ISSUE TITLE
Simple app to read and write smart contract

### ISSUE THREAD

**Issue by gupadhyaya** [harmony-one/hackathon#6]
Goals:
* Fork the repo https://github.com/defi-org-code/contract-reader
* Remove Ethereum and BSC configurations and replace it with harmony configurations to make it work
* Deploy a contract and publish its source on https://explorer.harmony.one (under contract tab of the deploy contract page)
* Try out the app to interact with the deployed contract
* Add a README.md file with instructions to the repo, also add a video tutorial of the whole demo and submit both

Reward
* 500 ONE w/o video
* 1000 ONE w/ video

**Comment by Severino** [comment]
How can I get the ABI of a contract on Harmony?
In the repo they query some ETH API for it.

If I get the ABI I can do that :wink:

**Comment by potvik** [comment]
For verified contracts: https://ctrver.t.hmny.io/fetchContractCode?contractAddress=one1pzgn6dfsj83ykdslpegeutm66pa83x2ax0tlxf

**Comment by Severino** [comment]
Superb! I tested it with the address and this should work. I just need to get the fromBech32() function to work in vanilla JS xD But can be done.

**Comment by Severino** [comment]
Done:
https://github.com/Severino/harmony-contract-reader

Will do a short video on the weekend.

With all the hiccups I worked approx. 3 hours.

Cheers

**Comment by Severino** [comment]
I have posted a short video here:
https://www.youtube.com/watch?v=p55uc0jgCd4

**Comment by Severino** [comment]
Here is my address:
one1t9sqr030dr05t9kdxq73rytewktu2e6rxqj23g

**Comment by givp** [comment]
Forked https://github.com/harmony-one/harmony-contract-reader @gupadhyaya please review

**Comment by gupadhyaya** [comment]
looks great @Severino

**Comment by givp** [comment]
@Severino https://explorer.harmony.one/tx/0x7bb8ffcc51ea1890f24b7b9e70de71982cd68c15d43924812cb3d4f8ae5a884b
