### ISSUE TITLE
Simple marketplace app

### ISSUE THREAD

**Issue by gupadhyaya** [harmony-one/hackathon#7]
Goals:
* Fork the repo: https://github.com/harmony-one/marketplace
* Add harmony configuration, deploy contracts, and make it work (similar example can be found in https://github.com/harmony-one/dbank/tree/master)
* Create a README file with instructions
* Create a video tutorial and submit both the modified repo and the link to video tutorial 

Reward
* 500 ONE w/o video
* 1000 ONE w/ video

**Comment by sprect8** [comment]
Hi I am interested in doing this

**Comment by givp** [comment]
> Hi I am interested in doing this

Good to go!

**Comment by sprect8** [comment]
Hi, I have submitted a PR for this issue at https://github.com/harmony-one/marketplace/pull/1

Video link: https://youtu.be/VveXzSvjFTA
My One Address: one1p9utfew9vn66jwucf87d89vr5cqnzl69pvfga9

Please review @givp and team, happy to modify as required.

**Comment by gupadhyaya** [comment]
> Hi, I have submitted a PR for this issue at [harmony-one/marketplace#1](https://github.com/harmony-one/marketplace/pull/1)
> 
> Video link: https://youtu.be/VveXzSvjFTA
> My One Address: one1p9utfew9vn66jwucf87d89vr5cqnzl69pvfga9
> 
> Please review @givp and team, happy to modify as required.

looks great @sprect8
could you change the tutorial title to "Tutorial on building a simple marketplace dapp on Harmony blockchain" and leave the credit to Dapp University in the description?

**Comment by givp** [comment]
@sprect8 are you able to improve the audio? I'm on max volume and can barely hear it

**Comment by sprect8** [comment]
Hi @gupadhyaya, @givp I have updated the youtube video, new link is 
https://youtu.be/ULUl5SPJ0FY (I increased the volume and changed the title).

**Comment by givp** [comment]
@sprect8 sounds much better. Please don't forget to credit Dapp University in the description as Ganesha said. Thanks!

**Comment by sprect8** [comment]
Hi @givp, @gupadhyaya, I've added the following description to the youtube video:

Tutorial on building a simple marketplace dapp on Harmony blockchain based on the Dapp University Marketplace example. Refer to https://github.com/sprect8/marketplace for more information

**Comment by givp** [comment]
Merged and added to projects.

**Comment by givp** [comment]
@sprect8 https://explorer.harmony.one/tx/0x4108ba1da2ef046bc965e097107fc1031e22b3ea4c8b1e700a4e1bafc09a8cfe

**Comment by sprect8** [comment]
@givp received with thanks!
