### ISSUE TITLE
Dapp Template for Harmony Dapps

### ISSUE THREAD

**Issue by gupadhyaya** [harmony-one/hackathon#9]
Goals:

* Fork the repo: https://github.com/harmony-one/dapp_template_v1
* Add harmony configuration, deploy contracts, and make it work (similar example can be found in https://github.com/harmony-one/dbank/tree/master)
* Create a README file with instructions
* Create a video tutorial and submit both the modified repo and the link to video tutorial

Reward
* 500 ONE w/o video
* 1000 ONE w/ video

**Comment by Severino** [comment]
I'll tackle this one! ;)

**Comment by givp** [comment]
> I'll tackle this one! ;)

Good to go!

**Comment by Severino** [comment]
Worked 12h. Had some issues as also some parts of the repo were deprechecated and the localnet experience is quite improvable.

PR:
harmony-one/dapp_template_v1#1

[~~video~~](#)

Cheers ;)

**Comment by givp** [comment]
@Severino Can you put the video on YouTube please? (Public) so we can embed etc

**Comment by Severino** [comment]
Here is the youtube link:
~~https://youtu.be/OojLvhxbrA4~~

**Comment by givp** [comment]
> Here is the youtube link:
> https://youtu.be/OojLvhxbrA4

@Severino the audio is echo-y - do you have a way to fix it? It's kinda hard to listen to.

**Comment by Severino** [comment]
Yeah, I know. :( I can do a voice over. Will do it on the weekend.

**Comment by Severino** [comment]
Okay I uploaded a revamped version:
https://youtu.be/J5F9LIedDdE

**Comment by givp** [comment]
Looks (and sounds) great. Thanks @Severino

**Comment by Severino** [comment]
Here is my address:
one1t9sqr030dr05t9kdxq73rytewktu2e6rxqj23g

**Comment by givp** [comment]
@Severino https://explorer.harmony.one/tx/0x23cce2ecb0b27c1739bbc6c7c44e21827307cd98b23cdf46e7839a0836f253f6
